import { readFile, writeFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const outputUrl = new URL("widget.js", root);
const sourceFiles = [
  "content.js",
  "disclosure-core.js",
  "app.js",
];

function removeModuleSyntax(source, file) {
  const withoutExports = source.replace(/^export\s+/gm, "");
  if (file !== "app.js") {
    return withoutExports;
  }

  const output = [];
  let insideImport = false;
  for (const line of withoutExports.split(/\r?\n/)) {
    if (!insideImport && line.startsWith("import ")) {
      insideImport = !line.includes(";");
      continue;
    }
    if (insideImport) {
      if (line.includes(";")) {
        insideImport = false;
      }
      continue;
    }
    output.push(line);
  }
  return output.join("\n");
}

export async function createRuntimeBundle() {
  const sections = [];
  for (const file of sourceFiles) {
    const source = await readFile(new URL(file, root), "utf8");
    sections.push(`// ${file}\n${removeModuleSyntax(source, file)}`);
  }

  return `/* Generated by scripts/build-runtime.mjs. Do not edit directly. */
(() => {
  "use strict";

${sections.join("\n\n")}
})();
`;
}

const bundle = await createRuntimeBundle();
if (process.argv.includes("--check")) {
  let existing = "";
  try {
    existing = await readFile(outputUrl, "utf8");
  } catch {
    // The comparison below reports a useful stale/missing artifact error.
  }
  if (existing !== bundle) {
    console.error(
      "widget.js is missing or stale. Run `npm.cmd run build` and commit the result.",
    );
    process.exitCode = 1;
  } else {
    console.log("Runtime bundle is current.");
  }
} else {
  await writeFile(outputUrl, bundle, "utf8");
  console.log(`Built widget.js from ${sourceFiles.length} tested source modules.`);
}
