/* Generated by scripts/build-runtime.mjs. Do not edit directly. */
(() => {
  "use strict";

// content.js
const WIDGET_ID = "B9-declaracio-compatible";
const WIDGET_VERSION = "2.0.0";

const ACTIVITY_CONVENTION = Object.freeze({
  id: "b9-activity-convention",
  version: "2026-07-24",
  title: "Convenció didàctica de l'activitat B9",
  disclaimer:
    "Aquesta és una convenció de pràctica, no una política institucional. La consigna de cada assignatura sempre té prioritat.",
  requiredGroupIds: ["tool", "purpose", "extent", "human"],
});

const OPENING_DECLARATION =
  "He fet servir IA per ajudar-me amb el document.";

const WORLDS = Object.freeze([
  {
    id: "proofread",
    title: "Corrector ortogràfic",
    description:
      "Va escriure tot el document i va acceptar correccions ortogràfiques suggerides per una eina d'IA.",
    profile: {
      purpose: "proofread",
      usedInSubmission: true,
      contribution: "spelling-only",
      humanRole: "authored-all-accepted-corrections",
    },
  },
  {
    id: "brainstorm",
    title: "Pluja d'idees prèvia",
    description:
      "Va explorar idees amb l'eina abans de redactar, va descartar-ne la sortida i va escriure tot el document.",
    profile: {
      purpose: "brainstorm",
      usedInSubmission: false,
      contribution: "discarded-ideas",
      humanRole: "authored-all-discarded-output",
    },
  },
  {
    id: "full-draft",
    title: "Document sencer generat",
    description:
      "Va demanar un esborrany complet del document i només hi va fer canvis menors.",
    profile: {
      purpose: "generate-document",
      usedInSubmission: true,
      contribution: "full-draft",
      humanRole: "lightly-edited-full-draft",
    },
  },
  {
    id: "outline-own-text",
    title: "Estructura generada, text propi",
    description:
      "Va demanar tres propostes d'estructura, en va combinar i reorganitzar una, i va escriure tot el text final.",
    profile: {
      purpose: "structure",
      usedInSubmission: true,
      contribution: "outline-only",
      humanRole: "reorganized-outline-authored-text",
    },
  },
  {
    id: "translation",
    title: "Traducció",
    description:
      "Va escriure el document en català, en va generar una traducció anglesa i va revisar-ne la terminologia.",
    profile: {
      purpose: "translate",
      usedInSubmission: true,
      contribution: "full-translation",
      humanRole: "authored-source-reviewed-translation",
    },
  },
  {
    id: "design-consultation",
    title: "Consultes de disseny",
    description:
      "Va fer preguntes sobre disseny de nivells, va aplicar algun consell i no va copiar cap text de l'eina.",
    profile: {
      purpose: "consult-design",
      usedInSubmission: false,
      contribution: "advice-only",
      humanRole: "authored-all-used-advice",
    },
  },
  {
    id: "generated-sections",
    title: "Dues seccions generades",
    description:
      "Va generar les seccions 2 i 4, les va conservar gairebé sense canvis i va escriure la resta.",
    profile: {
      purpose: "generate-sections",
      usedInSubmission: true,
      contribution: "sections-2-4",
      humanRole: "retained-generated-sections",
    },
  },
  {
    id: "outline-and-section",
    title: "Estructura i una secció",
    description:
      "Va generar l'estructura i la secció 4, va reorganitzar l'estructura i va retocar lleument la secció.",
    profile: {
      purpose: "outline-and-section",
      usedInSubmission: true,
      contribution: "outline-and-section-4",
      humanRole: "reorganized-outline-lightly-edited-section",
    },
  },
]);

const ALL_HUMAN_ROLES = WORLDS.map((world) => world.profile.humanRole);

const DISCLOSURE_GROUPS = Object.freeze([
  {
    id: "tool",
    stepLabel: "L'eina",
    legend: "1. Identifica l'ús d'IA",
    help:
      "Dir que hi ha hagut IA és imprescindible en aquesta activitat. El producte, el mode o la data poden afegir procedència, però no expliquen per si sols el procés.",
    required: true,
    options: [
      {
        id: "tool-none",
        label: "No dir-ho",
        sentence: "",
        where: {},
        fulfills: false,
        explanation: "Sense una menció explícita, el text no és una declaració d'ús d'IA.",
      },
      {
        id: "tool-generic",
        label: "«una eina d'IA generativa»",
        sentence: "He fet servir una eina d'IA generativa.",
        where: {},
        fulfills: true,
        explanation:
          "Declara l'ús, però no aporta procedència sobre el producte o el moment.",
      },
      {
        id: "tool-provenance",
        label: "«ChatGPT al web, juliol de 2026; model no registrat»",
        sentence:
          "He fet servir ChatGPT al web el juliol de 2026; no vaig registrar quin model exacte estava actiu.",
        where: {},
        fulfills: true,
        explanation:
          "Afegeix procedència amb honestedat. No separa els vuit casos perquè tots comparteixen aquesta dada en el conjunt de prova.",
      },
    ],
  },
  {
    id: "purpose",
    stepLabel: "La finalitat",
    legend: "2. Explica per a què",
    help:
      "La finalitat descriu la tasca concreta. «Ajudar-me» és cert en molts casos, però encara deixa gairebé tot per saber.",
    required: true,
    options: [
      {
        id: "purpose-none",
        label: "No dir-ho",
        sentence: "",
        where: {},
        fulfills: false,
        explanation: "Falta explicar quina tasca es va delegar o compartir amb l'eina.",
      },
      {
        id: "purpose-vague",
        label: "«per ajudar-me amb el document»",
        sentence:
          "La finalitat de l'ús d'IA era ajudar-me amb el document.",
        where: {},
        fulfills: true,
        vague: true,
        explanation:
          "Completa el camp, però no diferencia cap dels casos de prova.",
      },
      {
        id: "purpose-proofread",
        label: "«per corregir l'ortografia»",
        sentence:
          "La finalitat de l'ús d'IA era corregir l'ortografia del text.",
        where: { purpose: ["proofread"] },
        fulfills: true,
        explanation: "Descriu una correcció formal, no generació de contingut.",
      },
      {
        id: "purpose-brainstorm",
        label: "«per explorar idees abans de redactar»",
        sentence:
          "La finalitat de l'ús d'IA era explorar idees abans de redactar.",
        where: { purpose: ["brainstorm"] },
        fulfills: true,
        explanation: "Situa l'ús en la fase d'ideació.",
      },
      {
        id: "purpose-full-draft",
        label: "«per generar un esborrany complet»",
        sentence:
          "La finalitat de l'ús d'IA era generar un esborrany complet del document.",
        where: { purpose: ["generate-document"] },
        fulfills: true,
        explanation: "Declara generació de principi a fi.",
      },
      {
        id: "purpose-structure",
        label: "«per proposar estructures»",
        sentence:
          "La finalitat de l'ús d'IA era proposar estructures per al document.",
        where: { purpose: ["structure", "outline-and-section"] },
        fulfills: true,
        explanation:
          "Diferencia el treball sobre l'estructura, però encara no diu si també es va generar text.",
      },
      {
        id: "purpose-translate",
        label: "«per traduir el meu text»",
        sentence:
          "La finalitat de l'ús d'IA era traduir a l'anglès un text que jo havia escrit en català.",
        where: { purpose: ["translate"] },
        fulfills: true,
        explanation: "Identifica una transformació lingüística del text propi.",
      },
      {
        id: "purpose-consult",
        label: "«per consultar dubtes de disseny»",
        sentence:
          "La finalitat de l'ús d'IA era consultar dubtes de disseny de nivells.",
        where: { purpose: ["consult-design"] },
        fulfills: true,
        explanation: "Descriu assessorament, no generació de text per al lliurament.",
      },
      {
        id: "purpose-sections",
        label: "«per generar text d'una o més seccions concretes»",
        sentence:
          "La finalitat de l'ús d'IA era generar text per a una o més seccions concretes.",
        where: { purpose: ["generate-sections", "outline-and-section"] },
        fulfills: true,
        explanation:
          "Declara generació parcial; encara cal concretar quines parts.",
      },
    ],
  },
  {
    id: "extent",
    stepLabel: "L'abast",
    legend: "3. Delimita què va afectar",
    help:
      "Indica la fase, l'artefacte i l'abast. Aquesta dada evita que «al document» amagui diferències importants.",
    required: true,
    options: [
      {
        id: "extent-none",
        label: "No dir-ho",
        sentence: "",
        where: {},
        fulfills: false,
        explanation: "Falta delimitar quina part o fase va rebre la contribució d'IA.",
      },
      {
        id: "extent-document",
        label: "«va afectar el document lliurat»",
        sentence: "La intervenció d'IA va afectar el document lliurat.",
        where: { usedInSubmission: [true] },
        fulfills: true,
        vague: true,
        explanation:
          "És cert, però encara agrupa correcció, estructura, traducció i generació.",
      },
      {
        id: "extent-spelling",
        label: "«només les correccions ortogràfiques»",
        sentence:
          "La intervenció d'IA es va limitar a suggeriments ortogràfics sobre el text final.",
        where: { contribution: ["spelling-only"] },
        fulfills: true,
        explanation: "Delimita una intervenció formal i local.",
      },
      {
        id: "extent-no-output",
        label: "«cap fragment de la sortida no s'hi va incorporar directament»",
        sentence:
          "Cap fragment de la sortida de l'eina no es va incorporar directament al lliurament.",
        where: { usedInSubmission: [false] },
        fulfills: true,
        explanation:
          "Separa l'ús previ o consultiu de la incorporació directa de sortides.",
      },
      {
        id: "extent-full-draft",
        label: "«tot l'esborrany va ser generat»",
        sentence:
          "La intervenció d'IA va produir l'esborrany complet del document.",
        where: { contribution: ["full-draft"] },
        fulfills: true,
        explanation: "Declara que l'abast generat cobreix el document sencer.",
      },
      {
        id: "extent-outline-only",
        label: "«només l'estructura; cap paràgraf final»",
        sentence:
          "La intervenció d'IA es va limitar a propostes d'estructura; cap paràgraf del text final no va ser generat.",
        where: { contribution: ["outline-only"] },
        fulfills: true,
        explanation:
          "Diferencia amb precisió una bastida estructural del text final.",
      },
      {
        id: "extent-translation",
        label: "«la traducció anglesa de tot el text»",
        sentence:
          "La intervenció d'IA va produir una traducció anglesa de tot el text català.",
        where: { contribution: ["full-translation"] },
        fulfills: true,
        explanation: "Delimita la llengua, la transformació i l'abast complet.",
      },
      {
        id: "extent-sections",
        label: "«el text de les seccions 2 i 4»",
        sentence:
          "La intervenció d'IA va produir el text de les seccions 2 i 4.",
        where: { contribution: ["sections-2-4"] },
        fulfills: true,
        explanation: "Identifica exactament quines parts contenen text generat.",
      },
      {
        id: "extent-outline-section",
        label: "«l'estructura i el text de la secció 4»",
        sentence:
          "La intervenció d'IA va produir l'estructura i el text de la secció 4.",
        where: { contribution: ["outline-and-section-4"] },
        fulfills: true,
        explanation: "Separa dos tipus de contribució dins del mateix document.",
      },
    ],
  },
  {
    id: "human",
    stepLabel: "La teva contribució",
    legend: "4. Explica què vas fer tu",
    help:
      "«Ho he revisat» és difícil d'auditar. Digues què vas escriure, canviar, descartar o comprovar.",
    required: true,
    options: [
      {
        id: "human-none",
        label: "No dir-ho",
        sentence: "",
        where: {},
        fulfills: false,
        explanation: "Falta descriure la contribució o la verificació humana.",
      },
      {
        id: "human-reviewed",
        label: "«ho vaig revisar»",
        sentence: "Vaig revisar el resultat de l'eina.",
        where: { humanRole: ALL_HUMAN_ROLES },
        fulfills: true,
        vague: true,
        explanation:
          "És compatible amb tots els casos i no explica què es va comprovar o canviar.",
      },
      {
        id: "human-authored-all",
        label: "«vaig escriure tot el text final»",
        sentence: "Jo vaig escriure tot el text final.",
        where: {
          humanRole: [
            "authored-all-accepted-corrections",
            "authored-all-discarded-output",
            "reorganized-outline-authored-text",
            "authored-all-used-advice",
          ],
        },
        fulfills: true,
        explanation:
          "Aclareix l'autoria del text, però encara no descriu com es va usar la sortida.",
      },
      {
        id: "human-proofread",
        label: "«vaig escriure el text i acceptar correccions una per una»",
        sentence:
          "Jo vaig escriure tot el text i vaig acceptar les correccions ortogràfiques una per una.",
        where: { humanRole: ["authored-all-accepted-corrections"] },
        fulfills: true,
        explanation: "Descriu autoria i decisió humana sobre cada correcció.",
      },
      {
        id: "human-brainstorm",
        label: "«vaig descartar les idees i escriure el document»",
        sentence:
          "Jo vaig descartar la sortida de la pluja d'idees i vaig escriure tot el document.",
        where: { humanRole: ["authored-all-discarded-output"] },
        fulfills: true,
        explanation: "Explica què es va fer amb la sortida i qui va redactar.",
      },
      {
        id: "human-full-draft",
        label: "«només hi vaig fer canvis menors»",
        sentence:
          "Jo només vaig fer canvis menors sobre l'esborrany complet generat.",
        where: { humanRole: ["lightly-edited-full-draft"] },
        fulfills: true,
        explanation: "No infla una revisió lleu fins a convertir-la en autoria.",
      },
      {
        id: "human-outline",
        label: "«vaig reorganitzar l'estructura i escriure tot el text»",
        sentence:
          "Jo vaig combinar i reorganitzar una proposta d'estructura i vaig escriure tot el text final.",
        where: { humanRole: ["reorganized-outline-authored-text"] },
        fulfills: true,
        explanation: "Descriu la transformació de la bastida i l'autoria del text.",
      },
      {
        id: "human-translation",
        label: "«vaig escriure l'original i revisar la terminologia»",
        sentence:
          "Jo vaig escriure l'original català i vaig revisar la terminologia de la traducció anglesa.",
        where: { humanRole: ["authored-source-reviewed-translation"] },
        fulfills: true,
        explanation: "Separa l'autoria de l'original de la revisió de la traducció.",
      },
      {
        id: "human-consult",
        label: "«vaig aplicar consells sense copiar-ne el text»",
        sentence:
          "Jo vaig aplicar alguns consells de disseny, però no vaig copiar cap text de l'eina.",
        where: { humanRole: ["authored-all-used-advice"] },
        fulfills: true,
        explanation: "Descriu una influència conceptual sense incorporació de text.",
      },
      {
        id: "human-sections",
        label: "«vaig conservar les seccions gairebé sense canvis»",
        sentence:
          "Jo vaig conservar les seccions 2 i 4 gairebé sense canvis i vaig escriure la resta.",
        where: { humanRole: ["retained-generated-sections"] },
        fulfills: true,
        explanation: "Fa visible que la intervenció humana sobre les parts generades va ser mínima.",
      },
      {
        id: "human-outline-section",
        label: "«vaig reorganitzar l'estructura i retocar la secció»",
        sentence:
          "Jo vaig reorganitzar l'estructura i vaig fer retocs menors a la secció 4 generada.",
        where: { humanRole: ["reorganized-outline-lightly-edited-section"] },
        fulfills: true,
        explanation: "Descriu dues intervencions humanes diferents.",
      },
    ],
  },
]);

const WORKED_SCENARIO = Object.freeze({
  id: "worked-outline",
  title: "Cas guiat: estructura generada, text propi",
  targetWorldId: "outline-own-text",
  facts: [
    "L'eina va proposar tres estructures.",
    "L'estudiant en va combinar i reorganitzar una.",
    "L'estudiant va escriure tot el text final.",
    "Cap paràgraf final no va ser generat.",
  ],
  recommendedSelections: {
    tool: "tool-provenance",
    purpose: "purpose-structure",
    extent: "extent-outline-only",
    human: "human-outline",
  },
});

const TRANSFER_SCENARIOS = Object.freeze([
  {
    id: "transfer-brainstorm",
    title: "Idees descartades",
    targetWorldId: "brainstorm",
    summary:
      "Abans de redactar, l'estudiant va explorar idees amb l'eina. No en va conservar cap sortida i va escriure tot el document.",
    facts: [
      "Ús abans de la redacció.",
      "La sortida es va descartar.",
      "Cap text de l'eina no apareix al lliurament.",
      "L'estudiant va escriure tot el document.",
    ],
    recommendedSelections: {
      tool: "tool-generic",
      purpose: "purpose-brainstorm",
      extent: "extent-no-output",
      human: "human-brainstorm",
    },
  },
  {
    id: "transfer-translation",
    title: "Traducció revisada",
    targetWorldId: "translation",
    summary:
      "L'estudiant va escriure el document en català, en va generar la traducció anglesa completa i va revisar-ne la terminologia.",
    facts: [
      "L'original català és text propi.",
      "La traducció anglesa cobreix tot el document.",
      "L'estudiant va revisar la terminologia.",
    ],
    recommendedSelections: {
      tool: "tool-generic",
      purpose: "purpose-translate",
      extent: "extent-translation",
      human: "human-translation",
    },
  },
  {
    id: "transfer-sections",
    title: "Seccions conservades",
    targetWorldId: "generated-sections",
    summary:
      "L'eina va generar les seccions 2 i 4. L'estudiant les va conservar gairebé sense canvis i va escriure tota la resta.",
    facts: [
      "Les seccions 2 i 4 són text generat.",
      "Aquestes seccions es van conservar gairebé sense canvis.",
      "La resta del document és text propi.",
    ],
    recommendedSelections: {
      tool: "tool-generic",
      purpose: "purpose-sections",
      extent: "extent-sections",
      human: "human-sections",
    },
  },
]);

const LONG_VAGUE_SELECTIONS = Object.freeze({
  tool: "tool-provenance",
  purpose: "purpose-vague",
  extent: "extent-document",
  human: "human-reviewed",
});


// disclosure-core.js
function assertArray(value, name) {
  if (!Array.isArray(value)) {
    throw new TypeError(`${name} must be an array`);
  }
}

function getGroup(groups, groupId) {
  return groups.find((group) => group.id === groupId);
}

function getOption(groups, groupId, optionId) {
  const group = getGroup(groups, groupId);
  return group?.options.find((option) => option.id === optionId);
}

function clauseMatchesWorld(clause, world) {
  return Object.entries(clause.where ?? {}).every(([field, allowedValues]) => {
    assertArray(allowedValues, `where.${field}`);
    return allowedValues.includes(world.profile[field]);
  });
}

function selectedClauses(groups, selections) {
  return groups.flatMap((group) => {
    const optionId = selections[group.id];
    if (!optionId) {
      return [];
    }

    const option = getOption(groups, group.id, optionId);
    if (!option) {
      throw new Error(`Unknown option "${optionId}" for group "${group.id}"`);
    }

    return [{ group, option }];
  });
}

function compatibleWorlds(worlds, groups, selections) {
  const clauses = selectedClauses(groups, selections);
  return worlds.filter((world) =>
    clauses.every(({ option }) => clauseMatchesWorld(option, world)),
  );
}

function buildDeclaration(groups, selections) {
  return selectedClauses(groups, selections)
    .map(({ option }) => option.sentence.trim())
    .filter(Boolean)
    .join(" ");
}

function compareWorldSets(previousWorlds, currentWorlds) {
  const previousIds = new Set(previousWorlds.map((world) => world.id));
  const currentIds = new Set(currentWorlds.map((world) => world.id));

  return {
    removed: previousWorlds.filter((world) => !currentIds.has(world.id)),
    reopened: currentWorlds.filter((world) => !previousIds.has(world.id)),
    retained: currentWorlds.filter((world) => previousIds.has(world.id)),
  };
}

function evaluateDisclosure({
  worlds,
  groups,
  selections,
  targetWorldId,
  requiredGroupIds,
}) {
  const target = worlds.find((world) => world.id === targetWorldId);
  if (!target) {
    throw new Error(`Unknown target world "${targetWorldId}"`);
  }

  const clauses = selectedClauses(groups, selections);
  const compatible = compatibleWorlds(worlds, groups, selections);
  const compatibleIds = new Set(compatible.map((world) => world.id));

  const falseClauses = clauses.filter(
    ({ option }) => !clauseMatchesWorld(option, target),
  );

  const missingGroupIds = requiredGroupIds.filter((groupId) => {
    const optionId = selections[groupId];
    const option = optionId ? getOption(groups, groupId, optionId) : undefined;
    return !option?.fulfills;
  });

  const truthful = compatibleIds.has(targetWorldId);
  const complete = missingGroupIds.length === 0;
  const specific = compatible.length === 1;
  const selectedCount = clauses.length;

  let state = "empty";
  if (selectedCount > 0 && !truthful) {
    state = "contradiction";
  } else if (selectedCount > 0 && !complete) {
    state = "incomplete";
  } else if (selectedCount > 0 && !specific) {
    state = "ambiguous";
  } else if (selectedCount > 0) {
    state = "precise";
  }

  return {
    state,
    target,
    selectedCount,
    clauses,
    compatible,
    declaration: buildDeclaration(groups, selections),
    falseClauses,
    missingGroupIds,
    truthful,
    complete,
    specific,
    success: state === "precise",
  };
}

function findDuplicates(values) {
  const seen = new Set();
  const duplicates = new Set();
  for (const value of values) {
    if (seen.has(value)) {
      duplicates.add(value);
    }
    seen.add(value);
  }
  return [...duplicates];
}

function validateContent({
  worlds,
  groups,
  policy,
  scenarios,
}) {
  const errors = [];
  const worldIds = worlds.map((world) => world.id);
  const groupIds = groups.map((group) => group.id);
  const worldIdSet = new Set(worldIds);

  for (const duplicate of findDuplicates(worldIds)) {
    errors.push(`Duplicate world id: ${duplicate}`);
  }
  for (const duplicate of findDuplicates(groupIds)) {
    errors.push(`Duplicate group id: ${duplicate}`);
  }

  const globalOptionIds = [];
  for (const world of worlds) {
    if (!world.title || !world.description || !world.profile) {
      errors.push(`World ${world.id} is missing title, description, or profile`);
    }
  }

  for (const group of groups) {
    if (!group.legend || !group.help || !Array.isArray(group.options)) {
      errors.push(`Group ${group.id} is missing accessible content`);
      continue;
    }

    if (!group.options.some((option) => option.fulfills === false)) {
      errors.push(`Group ${group.id} has no explicit omission option`);
    }

    for (const duplicate of findDuplicates(
      group.options.map((option) => option.id),
    )) {
      errors.push(`Duplicate option id in ${group.id}: ${duplicate}`);
    }

    for (const option of group.options) {
      globalOptionIds.push(option.id);
      if (
        typeof option.label !== "string" ||
        typeof option.sentence !== "string" ||
        typeof option.explanation !== "string" ||
        typeof option.fulfills !== "boolean"
      ) {
        errors.push(`Option ${option.id} is missing required content`);
      }

      for (const [field, allowedValues] of Object.entries(option.where ?? {})) {
        if (!Array.isArray(allowedValues) || allowedValues.length === 0) {
          errors.push(`Option ${option.id} has an invalid where.${field}`);
          continue;
        }

        const knownValues = new Set(
          worlds
            .map((world) => world.profile[field])
            .filter((value) => value !== undefined),
        );
        if (knownValues.size === 0) {
          errors.push(`Option ${option.id} references unknown field ${field}`);
        }
        for (const value of allowedValues) {
          if (!knownValues.has(value)) {
            errors.push(
              `Option ${option.id} references unknown ${field} value ${String(value)}`,
            );
          }
        }
      }
    }
  }

  for (const duplicate of findDuplicates(globalOptionIds)) {
    errors.push(`Option id must be globally unique: ${duplicate}`);
  }

  for (const requiredGroupId of policy.requiredGroupIds) {
    if (!groupIds.includes(requiredGroupId)) {
      errors.push(`Policy references unknown group: ${requiredGroupId}`);
    }
  }

  for (const scenario of scenarios) {
    if (!worldIdSet.has(scenario.targetWorldId)) {
      errors.push(
        `Scenario ${scenario.id} references unknown target ${scenario.targetWorldId}`,
      );
      continue;
    }

    for (const groupId of policy.requiredGroupIds) {
      const optionId = scenario.recommendedSelections?.[groupId];
      if (!optionId || !getOption(groups, groupId, optionId)) {
        errors.push(
          `Scenario ${scenario.id} has no valid recommended option for ${groupId}`,
        );
      }
    }

    try {
      const result = evaluateDisclosure({
        worlds,
        groups,
        selections: scenario.recommendedSelections ?? {},
        targetWorldId: scenario.targetWorldId,
        requiredGroupIds: policy.requiredGroupIds,
      });
      if (!result.success) {
        errors.push(
          `Scenario ${scenario.id} recommended path ends in ${result.state}`,
        );
      }
    } catch (error) {
      errors.push(`Scenario ${scenario.id} cannot be evaluated: ${error.message}`);
    }
  }

  return errors;
}


// activity-flow.js
const ACTIVITY_STEPS = Object.freeze({
  PREDICTION: 1,
  WORKED_CASE: 2,
  REFLECTION: 3,
  TRANSFER: 4,
  TAKEAWAY: 5,
});

const FIRST_STEP = ACTIVITY_STEPS.PREDICTION;
const LAST_STEP = ACTIVITY_STEPS.TAKEAWAY;

function isValidStep(step) {
  return Number.isInteger(step) && step >= FIRST_STEP && step <= LAST_STEP;
}

class ActivityFlow {
  constructor() {
    this.currentStep = FIRST_STEP;
    this.predictionRevealed = false;
    this.workedCaseConfirmed = false;
    this.reflectionCorrect = false;
    this.transferConfirmed = false;
    this.completed = false;
  }

  revealPrediction() {
    this.predictionRevealed = true;
  }

  setWorkedCaseConfirmed(value) {
    this.workedCaseConfirmed = Boolean(value);
    if (!this.workedCaseConfirmed) {
      this.reflectionCorrect = false;
      this.transferConfirmed = false;
    }
  }

  setReflectionCorrect(value) {
    const accepted = Boolean(value) && this.workedCaseConfirmed;
    this.reflectionCorrect = accepted;
    if (!accepted) {
      this.transferConfirmed = false;
    }
    return accepted;
  }

  setTransferConfirmed(value) {
    const accepted = Boolean(value) && this.reflectionCorrect;
    this.transferConfirmed = accepted;
    return accepted;
  }

  canEnter(step) {
    if (!isValidStep(step)) {
      return false;
    }

    const requirements = {
      [ACTIVITY_STEPS.PREDICTION]: true,
      [ACTIVITY_STEPS.WORKED_CASE]: this.predictionRevealed,
      [ACTIVITY_STEPS.REFLECTION]: this.workedCaseConfirmed,
      [ACTIVITY_STEPS.TRANSFER]: this.reflectionCorrect,
      [ACTIVITY_STEPS.TAKEAWAY]: this.transferConfirmed,
    };
    return requirements[step];
  }

  enter(step) {
    if (!isValidStep(step)) {
      return false;
    }

    const movingBack = step < this.currentStep;
    if (!movingBack && !this.canEnter(step)) {
      return false;
    }

    this.currentStep = step;
    if (step === ACTIVITY_STEPS.TAKEAWAY) {
      this.completed = true;
    }
    return true;
  }

  resetTransfer() {
    this.transferConfirmed = false;
    if (this.currentStep > ACTIVITY_STEPS.TRANSFER) {
      this.currentStep = ACTIVITY_STEPS.TRANSFER;
    }
  }

  snapshot() {
    return Object.freeze({
      currentStep: this.currentStep,
      predictionRevealed: this.predictionRevealed,
      workedCaseConfirmed: this.workedCaseConfirmed,
      reflectionCorrect: this.reflectionCorrect,
      transferConfirmed: this.transferConfirmed,
      completed: this.completed,
    });
  }
}


// app.js

const REQUIRED_GROUPS = ACTIVITY_CONVENTION.requiredGroupIds;

function byId(id) {
  return document.getElementById(id);
}

function setStatusContent(element, title, detail) {
  const heading = document.createElement("strong");
  heading.textContent = title;
  const paragraph = document.createElement("p");
  paragraph.textContent = detail;
  element.replaceChildren(heading, paragraph);
}

function listFacts(element, facts) {
  element.replaceChildren(
    ...facts.map((fact) => {
      const item = document.createElement("li");
      item.textContent = fact;
      return item;
    }),
  );
}

function worldNames(worlds) {
  return worlds.map((world) => world.title).join(", ");
}

class MoodleBridge {
  constructor() {
    const configuredOrigin =
      document
        .querySelector('meta[name="enti-parent-origin"]')
        ?.getAttribute("content")
        ?.trim() ?? "";
    this.parentOrigin = this.normalizeOrigin(configuredOrigin);
    this.enabled = Boolean(
      this.parentOrigin && window.parent && window.parent !== window,
    );
    this.completionSent = false;
    this.resizeTimer = undefined;
  }

  normalizeOrigin(value) {
    if (!value) {
      return "";
    }
    try {
      const url = new URL(value);
      const originOnly =
        (url.protocol === "https:" || url.protocol === "http:") &&
        !url.username &&
        !url.password &&
        (url.pathname === "/" || url.pathname === "") &&
        !url.search &&
        !url.hash;
      return originOnly ? url.origin : "";
    } catch {
      return "";
    }
  }

  post(type, payload = {}) {
    if (!this.enabled) {
      return;
    }

    window.parent.postMessage(
      {
        namespace: "enti.ai-literacy.widget",
        type,
        protocolVersion: 1,
        widgetId: WIDGET_ID,
        widgetVersion: WIDGET_VERSION,
        ...payload,
      },
      this.parentOrigin,
    );
  }

  ready() {
    this.post("enti.widget.ready", {
      height: Math.ceil(document.documentElement.scrollHeight),
    });
  }

  progress(step) {
    this.post("enti.widget.progress", { step, total: 5 });
  }

  complete() {
    if (this.completionSent) {
      return;
    }
    this.completionSent = true;
    this.post("enti.widget.complete", { milestone: "transfer-case-complete" });
  }

  observeResize() {
    if (!this.enabled || !("ResizeObserver" in window)) {
      return;
    }

    this.resizeObserver = new ResizeObserver(() => {
      window.clearTimeout(this.resizeTimer);
      this.resizeTimer = window.setTimeout(() => {
        this.post("enti.widget.resize", {
          height: Math.ceil(document.documentElement.scrollHeight),
        });
      }, 120);
    });
    this.resizeObserver.observe(document.body);
  }
}

class DisclosureBuilder {
  constructor({ root, scenario, onStateChange }) {
    this.root = root;
    this.builderId = root.dataset.builderId;
    this.onStateChange = onStateChange;
    this.selections = {};
    this.groupIndex = 0;
    this.maxVisited = 0;
    this.lastTransition = null;
    this.confirmed = false;

    const fragment = byId("builder-template").content.cloneNode(true);
    root.replaceChildren(fragment);

    this.elements = {
      groupPosition: root.querySelector('[data-role="group-position"]'),
      groupTitle: root.querySelector('[data-role="group-title"]'),
      groupHelp: root.querySelector('[data-role="group-help"]'),
      groupHost: root.querySelector('[data-role="group-host"]'),
      previous: root.querySelector('[data-role="previous-group"]'),
      next: root.querySelector('[data-role="next-group"]'),
      declaration: root.querySelector('[data-role="declaration"]'),
      status: root.querySelector('[data-role="status"]'),
      qualityChecks: root.querySelector('[data-role="quality-checks"]'),
      transition: root.querySelector('[data-role="transition"]'),
      worldSummary: root.querySelector('[data-role="world-summary"]'),
      worldList: root.querySelector('[data-role="world-list"]'),
      groupJump: root.querySelector('[data-role="group-jump"]'),
    };

    this.elements.groupTitle.tabIndex = -1;
    this.elements.previous.addEventListener("click", () => this.previousGroup());
    this.elements.next.addEventListener("click", () => this.nextGroup());
    this.setScenario(scenario);
  }

  setScenario(scenario) {
    this.scenario = scenario;
    this.selections = {};
    this.groupIndex = 0;
    this.maxVisited = 0;
    this.lastTransition = null;
    this.confirmed = false;
    this.render();
  }

  reset() {
    this.setScenario(this.scenario);
  }

  loadSelections(selections) {
    const before = this.evaluate();
    this.selections = { ...selections };
    const after = this.evaluate();
    this.lastTransition = compareWorldSets(before.compatible, after.compatible);
    this.groupIndex = DISCLOSURE_GROUPS.length - 1;
    this.maxVisited = this.groupIndex;
    this.confirmed = false;
    this.render();
  }

  evaluate() {
    return evaluateDisclosure({
      worlds: WORLDS,
      groups: DISCLOSURE_GROUPS,
      selections: this.selections,
      targetWorldId: this.scenario.targetWorldId,
      requiredGroupIds: REQUIRED_GROUPS,
    });
  }

  select(groupId, optionId) {
    const before = this.evaluate();
    this.selections[groupId] = optionId;
    const after = this.evaluate();
    this.lastTransition = compareWorldSets(before.compatible, after.compatible);
    this.confirmed = false;
    this.renderSummary();
    this.renderGroupJump();
    this.updateNavigation();
  }

  previousGroup() {
    if (this.groupIndex === 0) {
      return;
    }
    this.groupIndex -= 1;
    this.confirmed = false;
    this.render();
    this.elements.groupTitle.focus();
  }

  nextGroup() {
    const currentGroup = DISCLOSURE_GROUPS[this.groupIndex];
    if (!this.selections[currentGroup.id]) {
      this.elements.status.focus();
      return;
    }

    if (this.groupIndex < DISCLOSURE_GROUPS.length - 1) {
      this.groupIndex += 1;
      this.maxVisited = Math.max(this.maxVisited, this.groupIndex);
      this.render();
      this.elements.groupTitle.focus();
      return;
    }

    const result = this.evaluate();
    this.confirmed = result.success;
    this.renderSummary();
    if (!result.success) {
      this.elements.status.focus();
    }
  }

  render() {
    this.renderGroup();
    this.renderSummary();
    this.renderGroupJump();
    this.updateNavigation();
  }

  renderGroup() {
    const group = DISCLOSURE_GROUPS[this.groupIndex];
    this.elements.groupPosition.textContent =
      `Camp ${this.groupIndex + 1} de ${DISCLOSURE_GROUPS.length}`;
    this.elements.groupTitle.textContent = group.legend;
    this.elements.groupHelp.textContent = group.help;

    const fieldset = document.createElement("fieldset");
    const legend = document.createElement("legend");
    legend.className = "visually-hidden";
    legend.textContent = group.legend;
    fieldset.append(legend);

    const choices = document.createElement("div");
    choices.className = "choice-list";

    for (const option of group.options) {
      const label = document.createElement("label");
      label.className = "choice choice-wide";

      const input = document.createElement("input");
      input.type = "radio";
      input.name = `${this.builderId}-${group.id}`;
      input.id = `${this.builderId}-${group.id}-${option.id}`;
      input.value = option.id;
      input.checked = this.selections[group.id] === option.id;
      input.addEventListener("change", () => this.select(group.id, option.id));

      const content = document.createElement("span");
      const title = document.createElement("strong");
      title.textContent = option.label;
      const explanation = document.createElement("small");
      explanation.textContent = option.explanation;
      content.append(title, explanation);
      label.append(input, content);
      choices.append(label);
    }

    fieldset.append(choices);
    this.elements.groupHost.replaceChildren(fieldset);
  }

  renderSummary() {
    const result = this.evaluate();
    const declaration =
      result.declaration || "Tria una opció per començar la declaració.";
    this.elements.declaration.textContent = declaration;
    this.elements.declaration.classList.toggle(
      "is-empty",
      !result.declaration,
    );

    this.elements.status.className = `builder-status status-${result.state}`;
    if (result.state === "empty") {
      setStatusContent(
        this.elements.status,
        "Encara no hi ha cap tria",
        "Comença pel camp actual. El cas real es mantindrà visible mentre construeixes.",
      );
    } else if (result.state === "contradiction") {
      const falseChoice = result.falseClauses[0];
      setStatusContent(
        this.elements.status,
        "Hi ha una contradicció",
        `La tria ${falseChoice.option.label} no coincideix amb el cas real. Revisa el camp «${falseChoice.group.stepLabel}».`,
      );
    } else if (result.state === "incomplete") {
      const labels = result.missingGroupIds
        .map((id) => getGroup(DISCLOSURE_GROUPS, id)?.stepLabel)
        .join(", ");
      setStatusContent(
        this.elements.status,
        "La declaració encara és incompleta",
        `Falten camps obligatoris: ${labels}. Un sol detall precís no substitueix una declaració completa.`,
      );
    } else if (result.state === "ambiguous") {
      setStatusContent(
        this.elements.status,
        "És fidel, però encara ambigua",
        `${result.compatible.length} casos de prova continuen sent compatibles. Afegeix un detall que descrigui el procés.`,
      );
    } else {
      setStatusContent(
        this.elements.status,
        "Declaració fidel, completa i precisa",
        "El cas real continua sent possible, els quatre camps són presents i cap altre cas de prova encaixa.",
      );
    }

    this.renderQualityChecks(result);
    this.renderTransition(result);
    this.renderCompatibleWorlds(result);
    this.onStateChange?.(result, { confirmed: this.confirmed });
  }

  renderQualityChecks(result) {
    const explicitTool = Boolean(
      getOption(
        DISCLOSURE_GROUPS,
        "tool",
        this.selections.tool,
      )?.fulfills,
    );
    const completedFields = REQUIRED_GROUPS.length - result.missingGroupIds.length;
    const checks = [
      {
        label: "Fidel al cas",
        value: result.truthful ? "sí" : "no",
        state: result.selectedCount === 0 ? "pending" : result.truthful ? "pass" : "fail",
      },
      {
        label: "Ús d'IA explícit",
        value: explicitTool ? "sí" : "falta",
        state: explicitTool ? "pass" : "fail",
      },
      {
        label: "Camps de pràctica",
        value: `${completedFields}/${REQUIRED_GROUPS.length}`,
        state: result.complete ? "pass" : "pending",
      },
      {
        label: "Casos encara compatibles",
        value: String(result.compatible.length),
        state: result.specific ? "pass" : result.truthful ? "pending" : "fail",
      },
      {
        label: "Ús permès",
        value: "mira la consigna",
        state: "pending",
      },
    ];

    this.elements.qualityChecks.replaceChildren(
      ...checks.map((check) => {
        const item = document.createElement("li");
        item.className = `is-${check.state}`;
        const mark = document.createElement("span");
        mark.className = "check-mark";
        mark.setAttribute("aria-hidden", "true");
        mark.textContent =
          check.state === "pass" ? "✓" : check.state === "fail" ? "×" : "·";
        const label = document.createElement("span");
        label.textContent = check.label;
        const value = document.createElement("span");
        value.className = "check-value";
        value.textContent = check.value;
        item.append(mark, label, value);
        return item;
      }),
    );
  }

  renderTransition(result) {
    if (!this.lastTransition || result.selectedCount === 0) {
      this.elements.transition.textContent = "";
      return;
    }

    const messages = [];
    if (this.lastTransition.removed.length > 0) {
      messages.push(
        `${this.lastTransition.removed.length} ${this.lastTransition.removed.length === 1 ? "cas descartat" : "casos descartats"}: ${worldNames(this.lastTransition.removed)}.`,
      );
    }
    if (this.lastTransition.reopened.length > 0) {
      messages.push(
        `${this.lastTransition.reopened.length} ${this.lastTransition.reopened.length === 1 ? "cas reobert" : "casos reoberts"}: ${worldNames(this.lastTransition.reopened)}.`,
      );
    }
    if (messages.length === 0) {
      messages.push(
        "Aquesta tria no separa els casos de prova. Pot completar o documentar un camp, però no explica per si sola el procés.",
      );
    }

    this.elements.transition.textContent = messages.join(" ");
  }

  renderCompatibleWorlds(result) {
    this.elements.worldSummary.textContent =
      result.compatible.length === 0
        ? "Cap cas compatible"
        : `${result.compatible.length} ${result.compatible.length === 1 ? "cas encara compatible" : "casos encara compatibles"}`;

    if (result.compatible.length === 0) {
      const item = document.createElement("li");
      item.textContent =
        "Les tries es contradiuen. Revisa el camp indicat abans de continuar.";
      this.elements.worldList.replaceChildren(item);
      return;
    }

    this.elements.worldList.replaceChildren(
      ...result.compatible.map((world) => {
        const item = document.createElement("li");
        if (world.id === this.scenario.targetWorldId) {
          item.classList.add("is-target");
        }
        const title = document.createElement("strong");
        title.textContent =
          world.id === this.scenario.targetWorldId
            ? `${world.title} · cas real`
            : world.title;
        const description = document.createElement("span");
        description.textContent = world.description;
        item.append(title, description);
        return item;
      }),
    );
  }

  renderGroupJump() {
    this.elements.groupJump.replaceChildren(
      ...DISCLOSURE_GROUPS.map((group, index) => {
        const button = document.createElement("button");
        button.type = "button";
        button.textContent = `${index + 1}. ${group.stepLabel}`;
        button.disabled = index > this.maxVisited;
        if (index === this.groupIndex) {
          button.setAttribute("aria-current", "step");
        }
        const option = getOption(
          DISCLOSURE_GROUPS,
          group.id,
          this.selections[group.id],
        );
        if (option?.fulfills) {
          button.classList.add("is-complete");
        }
        button.addEventListener("click", () => {
          this.groupIndex = index;
          this.confirmed = false;
          this.render();
          this.elements.groupTitle.focus();
        });
        return button;
      }),
    );
  }

  updateNavigation() {
    const group = DISCLOSURE_GROUPS[this.groupIndex];
    this.elements.previous.disabled = this.groupIndex === 0;
    this.elements.next.disabled = !this.selections[group.id];
    this.elements.next.textContent =
      this.groupIndex === DISCLOSURE_GROUPS.length - 1
        ? "Comprova la declaració"
        : "Camp següent";
  }
}

const contentErrors = validateContent({
  worlds: WORLDS,
  groups: DISCLOSURE_GROUPS,
  policy: ACTIVITY_CONVENTION,
  scenarios: [WORKED_SCENARIO, ...TRANSFER_SCENARIOS],
});

if (contentErrors.length > 0) {
  const notice = document.createElement("div");
  notice.className = "notice notice-error";
  notice.setAttribute("role", "alert");
  notice.textContent =
    "L'activitat no s'ha pogut carregar perquè el contingut no ha superat la validació.";
  byId("activity").prepend(notice);
  throw new Error(contentErrors.join("\n"));
}

const bridge = new MoodleBridge();
const activityFlow = new ActivityFlow();
let transferBuilder;
let transferScenario;

function updateProgress(step) {
  document.querySelectorAll("[data-progress-step]").forEach((item) => {
    const itemStep = Number(item.dataset.progressStep);
    item.classList.toggle("is-complete", itemStep < step);
    if (itemStep === step) {
      item.setAttribute("aria-current", "step");
    } else {
      item.removeAttribute("aria-current");
    }
  });
}

function showStep(step, { focus = true } = {}) {
  if (!activityFlow.enter(step)) {
    return false;
  }

  document.querySelectorAll(".activity-step").forEach((section) => {
    section.hidden = Number(section.dataset.step) !== step;
  });
  updateProgress(step);
  bridge.progress(step);

  if (step === 5) {
    const result = transferBuilder?.evaluate();
    byId("final-declaration").textContent =
      result?.declaration ?? "No hi ha cap declaració disponible.";
    bridge.complete();
  }

  if (focus) {
    const heading = document.querySelector(
      `.activity-step[data-step="${step}"] h2`,
    );
    heading?.focus();
  }
  return true;
}

function renderOpeningWorlds() {
  byId("opening-worlds").replaceChildren(
    ...WORLDS.map((world) => {
      const article = document.createElement("article");
      article.className = "world-card";
      const title = document.createElement("h3");
      title.textContent = world.title;
      const description = document.createElement("p");
      description.textContent = world.description;
      article.append(title, description);
      return article;
    }),
  );
}

function resetTransferState() {
  document
    .querySelectorAll('input[name="transfer-scenario"]')
    .forEach((input) => {
      input.checked = false;
    });
  byId("transfer-workspace").hidden = true;
  byId("to-step-5").hidden = true;
  transferScenario = undefined;
  transferBuilder = undefined;
  activityFlow.resetTransfer();
  byId("transfer-builder").replaceChildren();
}

function resetReflectionAndTransferState() {
  document
    .querySelectorAll('input[name="reflection"]')
    .forEach((input) => {
      input.checked = false;
    });
  byId("reflection-feedback").hidden = true;
  byId("to-step-4").hidden = true;
  activityFlow.setReflectionCorrect(false);
  resetTransferState();
}

byId("prediction-form").addEventListener("submit", (event) => {
  event.preventDefault();
  const selected = document.querySelector(
    'input[name="prediction"]:checked',
  );
  if (!selected) {
    const first = document.querySelector('input[name="prediction"]');
    first.setCustomValidity("Tria una resposta abans de continuar.");
    first.reportValidity();
    first.addEventListener(
      "change",
      () => first.setCustomValidity(""),
      { once: true },
    );
    return;
  }

  const guessedEight = selected.value === "8";
  byId("prediction-result").hidden = false;
  setStatusContent(
    byId("prediction-status"),
    guessedEight ? "Exacte: tots vuit" : `Has triat ${selected.value}; la resposta és 8`,
    "La frase no concreta ni la tasca, ni l'abast, ni què va fer l'estudiant. Per això tots els processos encara hi caben.",
  );
  renderOpeningWorlds();
  activityFlow.revealPrediction();
});

byId("to-step-2").addEventListener("click", () => showStep(2));

byId("worked-case-title").textContent = WORKED_SCENARIO.title;
listFacts(byId("worked-case-facts"), WORKED_SCENARIO.facts);

const workedBuilder = new DisclosureBuilder({
  root: byId("worked-builder"),
  scenario: WORKED_SCENARIO,
  onStateChange: (result, { confirmed }) => {
    const accepted = result.success && confirmed;
    activityFlow.setWorkedCaseConfirmed(accepted);
    byId("to-step-3").hidden = !accepted;
    if (!accepted) {
      resetReflectionAndTransferState();
    }
  },
});

byId("load-vague").addEventListener("click", () => {
  workedBuilder.loadSelections(LONG_VAGUE_SELECTIONS);
});
byId("reset-worked").addEventListener("click", () => workedBuilder.reset());
byId("to-step-3").addEventListener("click", () => showStep(3));

byId("reflection-form").addEventListener("submit", (event) => {
  event.preventDefault();
  const selected = document.querySelector(
    'input[name="reflection"]:checked',
  );
  if (!selected) {
    const first = document.querySelector('input[name="reflection"]');
    first.setCustomValidity("Tria una resposta abans de continuar.");
    first.reportValidity();
    first.addEventListener(
      "change",
      () => first.setCustomValidity(""),
      { once: true },
    );
    return;
  }

  const feedback = byId("reflection-feedback");
  feedback.hidden = false;
  const correct = selected.value === "process";
  feedback.className = `notice ${correct ? "notice-success" : "notice-error"}`;
  setStatusContent(
    feedback,
    correct ? "Correcte" : "Encara no",
    correct
      ? "La part afectada, l'abast i la contribució humana descriuen el repartiment del procés. La procedència de l'eina pot ser necessària, però no substitueix aquests detalls."
      : "El producte o la llargada poden afegir context, però no expliquen com es va repartir el treball. Torna-ho a provar.",
  );
  activityFlow.setReflectionCorrect(correct);
  byId("to-step-4").hidden = !correct;
  if (!correct) {
    resetTransferState();
  }
});

byId("to-step-4").addEventListener("click", () => showStep(4));

function renderScenarioChoices() {
  byId("scenario-choices").replaceChildren(
    ...TRANSFER_SCENARIOS.map((scenario) => {
      const label = document.createElement("label");
      label.className = "choice";
      const input = document.createElement("input");
      input.type = "radio";
      input.name = "transfer-scenario";
      input.value = scenario.id;
      const content = document.createElement("span");
      const title = document.createElement("strong");
      title.textContent = scenario.title;
      const summary = document.createElement("small");
      summary.textContent = scenario.summary;
      content.append(title, summary);
      label.append(input, content);
      return label;
    }),
  );
}

renderScenarioChoices();

byId("scenario-form").addEventListener("change", (event) => {
  const selectedId = event.target.value;
  transferScenario = TRANSFER_SCENARIOS.find(
    (scenario) => scenario.id === selectedId,
  );
  if (!transferScenario) {
    return;
  }

  byId("transfer-workspace").hidden = false;
  byId("transfer-case-title").textContent = transferScenario.title;
  byId("transfer-case-summary").textContent = transferScenario.summary;
  listFacts(byId("transfer-case-facts"), transferScenario.facts);
  activityFlow.setTransferConfirmed(false);
  byId("to-step-5").hidden = true;

  if (!transferBuilder) {
    transferBuilder = new DisclosureBuilder({
      root: byId("transfer-builder"),
      scenario: transferScenario,
      onStateChange: (result, { confirmed }) => {
        const accepted = result.success && confirmed;
        activityFlow.setTransferConfirmed(accepted);
        byId("to-step-5").hidden = !accepted;
      },
    });
  } else {
    transferBuilder.setScenario(transferScenario);
  }
});

byId("to-step-5").addEventListener("click", () => showStep(5));

document.querySelectorAll("[data-go-step]").forEach((button) => {
  button.addEventListener("click", () => {
    showStep(Number(button.dataset.goStep));
  });
});

byId("copy-declaration").addEventListener("click", async () => {
  const text = byId("final-declaration").textContent.trim();
  try {
    await navigator.clipboard.writeText(text);
    byId("copy-status").textContent =
      "Declaració copiada. Revisa-la contra la consigna abans d'entregar.";
  } catch {
    byId("copy-status").textContent =
      "El navegador no ha permès copiar-la. Selecciona el text i copia'l manualment.";
  }
});

byId("try-another").addEventListener("click", () => {
  resetTransferState();
  showStep(4);
});

byId("restart-activity").addEventListener("click", () => {
  window.location.reload();
});

bridge.ready();
bridge.observeResize();
showStep(ACTIVITY_STEPS.PREDICTION, { focus: false });
byId("startup-status").hidden = true;
document.documentElement.dataset.widgetReady = "true";

})();
